### ISSUE TITLE
warning: shared-lib-calls-exit in libglvnd 

### ISSUE THREAD

**Issue by kwizart** [NVIDIA/libglvnd#106]
There are few minors issues with libglvnd package as reported by rpmlint.

```
libglvnd.armv7hl: W: shared-lib-calls-exit /usr/lib/libGLX.so.0.0.0 exit@GLIBC_2.4
libglvnd.i686: W: shared-lib-calls-exit /usr/lib/libGLX.so.0.0.0 exit@GLIBC_2.0
libglvnd.x86_64: W: shared-lib-calls-exit /usr/lib64/libGLX.so.0.0.0 exit@GLIBC_2.2.5
```

This is caused by the (bundled) uthash library to handle fatal errors such as:
`#define uthash_fatal(msg) exit(-1)        /* fatal error (out of memory,etc) */`

rpmlint notice about shared-lib-calls-exit:

> This library package calls exit() or _exit(), probably in a non-fork()
> context. Doing so from a library is strongly discouraged - when a library
> function calls exit(), it prevents the calling program from handling the
> error, reporting it to the user, closing files properly, and cleaning up any
> state that the program has. It is preferred for the library to return an
> actual error code and let the calling program decide how to handle the
> situation.

Is this notice relevant for libglvnd ?
I've forwarded to utash:
https://github.com/troydhanson/uthash/issues/92

**Comment by kbrenneman** [comment]
We've migrated the repository over to GitLab, so this is now tracked at https://gitlab.freedesktop.org/glvnd/libglvnd/issues/106.
