### ISSUE TITLE
Error: shlib-with-non-pic-code in libglvnd for x86 32bit

### ISSUE THREAD

**Issue by kwizart** [NVIDIA/libglvnd#108]
rpmlint on i686 packages is reporting this issue.

```
libglvnd.i686: E: shlib-with-non-pic-code /usr/lib/libGLdispatch.so.0.0.0
libglvnd.i686: E: shlib-with-non-pic-code /usr/lib/libOpenGL.so.0.0.0
```

rpmlint -I shlib-with-non-pic-code:

> shlib-with-non-pic-code:
> 
> The listed shared libraries contain object code that was compiled without
> -fPIC. All object code in shared libraries should be recompiled separately
> from the static libraries with the -fPIC option.  Another common mistake that
> causes this problem is linking with `gcc -Wl,-shared'' instead of`gcc
> -shared''.

Is there a way to fix theses ?
Enforcing --with-pic doesn't seem to have any effect.

**Comment by kbrenneman** [comment]
It might be complaining about something in the assembly code for the dispatch stubs. Does the error go away if you build it with --disable-asm?

**Comment by kwizart** [comment]
Yes, I confirm that using --disable-asm in x86 32bit build make the issue disappear.

**Comment by kbrenneman** [comment]
Okay, that at least confirms that it's something in the assembly code. Do the x86 TLS stubs in #95 fare any better?

If so, then just merging that and using the TLS stubs by default might be easier.

**Comment by kwizart** [comment]
So I confirm that the PR#95 doesn't have the issue
I haven't done any runtime usability test.
