### ISSUE TITLE
libglvnd doesn't compile with x32 ABI

### ISSUE THREAD

**Issue by tycho** [NVIDIA/libglvnd#115]
The x86_64 ABI stubs don't compile or support the ILP32 x86_64 ABI (a.k.a. x32 ABI):
```
./src/GLdispatch/vnd-glapi/entry_x86_64_tsd.c
./src/GLdispatch/vnd-glapi/entry_x86_64_common.c
./src/GLdispatch/vnd-glapi/entry_x86_64_tls.c
```
ABI information here: https://sites.google.com/site/x32abi/documents

I'd really like to see support for this since I can currently use OpenGL *without* libglvnd on x32 using Mesa.

**Comment by kbrenneman** [comment]
I'll have to read up more on x32 to figure out how to implement assembly stubs for it.

In the meantime, though, you can configure libglvnd with --disable-asm, and it'll use C functions for the built-in dispatch stubs. It won't be able to generate stubs at runtime for new extension functions, but the built-in stubs cover almost every GL function from Mesa.

**Comment by mattst88** [comment]
Probably not a lot more than taking the recent commit 89458366585c34879b70110758bb4fd3acb62ce0 from Mesa would be needed for x32 support.

**Comment by kbrenneman** [comment]
Thanks for the Mesa pointer -- the stubs from Mesa seem to work well for libGLdispatch, and the generated code for GLX entrypoints and the unit tests were simple enough that they only needed some minor tweaking.
