### ISSUE TITLE
where is autogen.sh and configure

### ISSUE THREAD

**Issue by dawnsparrow** [NVIDIA/libglvnd#144]
the README document shows that Run ./autogen.sh, then run ./configure and make.
but where is the file exactly

dawn@cv:~$ locate autogen.sh
/lib/firmware/carl9170fw/autogen.sh
/usr/src/linux-headers-4.10.0-28/spl/autogen.sh
/usr/src/linux-headers-4.10.0-28/tools/usb/usbip/autogen.sh
/usr/src/linux-headers-4.10.0-28/zfs/autogen.sh
/usr/src/linux-headers-4.13.0-26/spl/autogen.sh
/usr/src/linux-headers-4.13.0-26/tools/usb/usbip/autogen.sh
/usr/src/linux-headers-4.13.0-26/zfs/autogen.sh
/usr/src/linux-headers-4.4.0-109/spl/autogen.sh
/usr/src/linux-headers-4.4.0-109/tools/usb/usbip/autogen.sh
/usr/src/linux-headers-4.4.0-109/zfs/autogen.sh

**Comment by aaronp24** [comment]
autogen.sh is part of the libglvnd repository: https://github.com/NVIDIA/libglvnd/blob/master/autogen.sh

When you clone libglvnd, it'll be in the libglvnd/ subdirectory of whatever directory you cloned it into.

configure is generated in the same directory when you run autogen.sh.
