### ISSUE TITLE
What is the procedure for installing libglvnd for RHEL 7.5

### ISSUE THREAD

**Issue by queglay** [NVIDIA/libglvnd#170]
Would it be possible to get the procedure for installing libglvnd in RHEL 7.5?

**Comment by queglay** [comment]
Thanks for letting me know.  I am using cuda 10!

**Comment by kwizart** [comment]
Copied from https://bugzilla.redhat.com/show_bug.cgi?id=1644446#c19

In case some would be still waiting for a workaround, you can grab the old EPEL package from there: 
https://koji.fedoraproject.org/koji/buildinfo?buildID=1096712

CentOS will publish a pre-version of the next RHEL in the CentOS-CR repo so it will be easier to grab in advances until CentOS 7.6-18.10 officially launched.
https://wiki.centos.org/AdditionalResources/Repositories/CR
http://mirror.centos.org/centos/$releasever/cr/

For RHEL, one can grab RHEL 7.6 mesa and libglvnd rpms via their respectives subscriptions.

For cuda 9.2 users:
I recommends to install the xorg-x11-drv-nvidia-390xx from RPM Fusion nonfree
This package does not make use of libglvnd (yet).

For cuda 10.0 users:
I recommends to install the xorg-x11-drv-nvidia from RPM Fusion nonfree for EL.
This package does make use of libglvnd. (so you need either the old libglvnd of the newer along with mesa).

**Comment by queglay** [comment]
Thankyou Nicolas this is all really helpful

**Comment by kbrenneman** [comment]
Closing, since there doesn't look to be anything else needed from the libglvnd side.
