### ISSUE TITLE
glx breaks after install

### ISSUE THREAD

**Issue by DocMAX** [NVIDIA/libglvnd#172]
After make install i get this (works before make install):
My CPU is Intel Onboard (i5 4690k).

```
[root@game libglvnd]# glxinfo
name of display: :0
Error: couldn't find RGB GLX visual or fbconfig
B GLX visual or fbconfig
```
And here my xorg.log:

```
[  1569.867] (II) Initializing extension GLX
[  1569.875] (II) AIGLX: Loaded and initialized i965
[  1569.875] (II) GLX: Initialized DRI2 GL provider for screen 0
```

**Comment by kbrenneman** [comment]
Libglvnd requires a driver that's built for libglvnd. To use libglvnd, you'd also need to build and install a libglvnd-enabled version of Mesa. You'll probably also need an updated version of the X server as well, because that's what libglvnd relies on to know which driver to load.

**Comment by DocMAX** [comment]
Is this documented somewhere? (What exactly is needed to have Intel, Nouveau, Nvidia, AMD in parallel)

**Comment by kbrenneman** [comment]
What's needed would be to download, build, and install a libglvnd-enabled version of Mesa.

Generally, though, you're better off using whatever packages your distro has. If your distro doesn't provide packages for libglvnd and a libglvnd-based version of Mesa, then a newer version of the distro might (depending on which distro you're using, obviously).
