### ISSUE TITLE
OpenGL headless on EGL with libglvnd without X11/GLX

### ISSUE THREAD

**Issue by likewise** [NVIDIA/libglvnd#175]
I would like to run OpenGL headless on EGL, instead of using GLES2/3 on EGL.

I was pointed here by #dri-render that libglvnd supports this, as the X11 dependency could be removed for the EGL-only case. However, the docs seem to indicate the X11 dependency is (again) baked-in.

Can GLX support be made configurable?

**Comment by kbrenneman** [comment]
Are you concerned about a run-time dependency or a build-time dependency?

**Comment by aritger** [comment]
To use EGL+OpenGL without X11, link against libEGL.so for EGL entry points, and libOpenGL.so for OpenGL entry points.  Neither of those libraries should have any X11 dependencies.

X11 should only come into play if you used GLX, either directly through the libGLX.so library (provides GLX entry points), or indirectly through the legacy libGL.so library (which provides both GLX and OpenGL entry points, for historical and backwards compatibility reasons).

**Comment by likewise** [comment]
I am concerned with all dependencies, both build-time, footprint in the final rootfs and run-time. I have globally disabled X11 for my targeted system and I would like to have a minimal set of libraries that offer me OpenGL/EGL and GLES/EGL.

I am trying to see where I can remove X11 from libglvnd, ideally it would be configurable whether libglvnd has X11 support at all (like the rest of the graphics stack).

libglvnd-1.1.0/include/EGL/eglplatform.h:99:10: fatal error: X11/Xlib.h

**Comment by likewise** [comment]
So probably the issue is elsewhere (mesa in my case). The other issue is that the mesa people tell the exact same. I have just tried removing the X11 dependency in libglvnd, which was actually quite easy. However that didn't convince mesa to build OpenGL for m, although it did tell OpenGL: yes (ES1: yes ES2: yes). I'll close this topic and move over to the other side again. Disclaimer: My *other* machines *are* running NVidia.
