### ISSUE TITLE
Autoselection of OpenGL backend may file with X forwarding

### ISSUE THREAD

**Issue by grisuthedragon** [NVIDIA/libglvnd#181]
On RHEL7/CentOS7 the GLdispatch approach is used by default. This leads on my system to a strange situation using ssh X11 forwarding. 

**Server:** CentOS 7, 2x K20 cards, CUDA 10.1, no running X 

**Client:** Ubuntu 16.04, X with nouveau driver. 

If the OpenGL libs are installed on the server, i.e. the package nvidia-driver-latest-dkms-libs-418.87.00-2.el7.x86_64 is installed, and I run glxinfo I get:
```
$ glxinfo
name of display: localhost:11.0
X Error of failed request:  BadValue (integer parameter out of range for operation)
  Major opcode of failed request:  155 (GLX)
  Minor opcode of failed request:  24 (X_GLXCreateNewContext)
  Value in failed request:  0x0
  Serial number of failed request:  39
  Current serial number in output stream:  40
```

If the package is not installed or the libraries matching '/usr/lib64/lin[EG]*nvidia*' are moved somewhere, the GL implementation from mesa is used and everything works: 
```
$ glxinfo
name of display: localhost:11.0
display: localhost:11  screen: 0
direct rendering: Yes
server glx vendor string: SGI
server glx version string: 1.4
server glx extensions:
    GLX_ARB_create_context, GLX_ARB_create_context_profile, 
    GLX_ARB_fbconfig_float, GLX_ARB_framebuffer_sRGB, GLX_ARB_multisample, 
    GLX_EXT_create_context_es2_profile, GLX_EXT_create_context_es_profile, 
    GLX_EXT_fbconfig_packed_float, GLX_EXT_framebuffer_sRGB, 
    GLX_EXT_import_context, GLX_EXT_texture_from_pixmap, GLX_EXT_visual_info, 
    GLX_EXT_visual_rating, GLX_INTEL_swap_event, GLX_MESA_copy_sub_buffer, 
    GLX_OML_swap_method, GLX_SGIS_multisample, GLX_SGIX_fbconfig, 
    GLX_SGIX_pbuffer, GLX_SGIX_visual_select_group, GLX_SGI_swap_control
client glx vendor string: Mesa Project and SGI
client glx version string: 1.4
client glx extensions:
    GLX_ARB_context_flush_control, GLX_ARB_create_context, 
    GLX_ARB_create_context_profile, GLX_ARB_create_context_robustness, 
    GLX_ARB_fbconfig_float, GLX_ARB_framebuffer_sRGB, 
    GLX_ARB_get_proc_address, GLX_ARB_multisample, GLX_EXT_buffer_age, 
    GLX_EXT_create_context_es2_profile, GLX_EXT_create_context_es_profile, 
    GLX_EXT_fbconfig_packed_float, GLX_EXT_framebuffer_sRGB, 
    GLX_EXT_import_context, GLX_EXT_texture_from_pixmap, GLX_EXT_visual_info, 
    GLX_EXT_visual_rating, GLX_INTEL_swap_event, GLX_MESA_copy_sub_buffer, 
    GLX_MESA_multithread_makecurrent, GLX_MESA_query_renderer, 
    GLX_MESA_swap_control, GLX_OML_swap_method, GLX_OML_sync_control, 
    GLX_SGIS_multisample, GLX_SGIX_fbconfig, GLX_SGIX_pbuffer, 
    GLX_SGIX_visual_select_group, GLX_SGI_make_current_read, 
    GLX_SGI_swap_control, GLX_SGI_video_sync
GLX version: 1.4
GLX extensions:
    GLX_ARB_create_context, GLX_ARB_create_context_profile, 
    GLX_ARB_fbconfig_float, GLX_ARB_framebuffer_sRGB, 
...
```
and everything works. 

Is there a way to bypass the autodetection of GLDispatch? or if not it should be, e.g. in terms of an enviroment variable like 
```
 export GLDISPATCH_USE=mesa/nvidia/... 
```

Otherwise I get introuble even with easy OpenGL applications like the QT based function plotter in octave.

**Comment by kbrenneman** [comment]
I'm actually more surprised that the second case worked, since the X server in Ubuntu 16.04 doesn't allow indirect rendering by default.

In any case, you've got two options for making that work. One is to override the vendor that libglvnd tries to load, and the other is to enable indirect rendering in the X server.

You can set an environment variable to tell libglvnd to use a specific vendor library like this:
```
__GLX_VENDOR_LIBRARY_NAME=mesa
```

Enabling indirect rendering in the server should let GLX work regardless of which vendor happens to get loaded -- any vendor will speak the same GLX protocol. To do that, you'd need to add "+iglx" to the X server command line. On Ubuntu, that probably means changing the GDM or lightdm config file.

**Comment by kbrenneman** [comment]
You could also change the libGLX_indirect.so.0 symlink to point to libGLX_mesa.so.0 instead of libGLX_nvidia.so.0, though that might get overwritten the next time you update the nvidia packages.

**Comment by grisuthedragon** [comment]
I did not add "+iglx" to the command line of X, it works fine without it. The `__GLX_VENDOR_LIBRARY_NAME` variable did the job. But then the bug is that it is not documented in the project, that this variable exists. When I grep for `__GLX_VENDOR_LIBRARY_NAME` in the source code I only find it in two code files and some shell scripts for the tests. So it would be great to mention it in the projects README such that one get to know about this possibility.

**Comment by kbrenneman** [comment]
We've migrated the repository over to GitLab, so this issue is now tracked at https://gitlab.freedesktop.org/glvnd/libglvnd/issues/181 .
