### ISSUE TITLE
Please document EGL vendor ICD search path

### ISSUE THREAD

**Issue by smcv** [NVIDIA/libglvnd#187]
I'm currently working on some code that needs to mirror EGL vendor ICDs from the host system into a container, so I need to be able to enumerate EGL vendor ICDs on the host system in the same way that GLVND would.

The current documentation in README is:

> In order to find the available vendor libraries, each vendor provides a JSON file in a well-known directory, similar to how Vulkan ICD's are loaded.

Here is what I've been able to piece together from the implementation, which can perhaps be a basis for more formal documentation:

## ICD discovery

* If the environment variable `__EGL_VENDOR_LIBRARY_FILENAMES` is set, it is a colon-separated list of JSON filenames. The ICDs described in those files are loaded, in the order given. No other ICDs are loaded.

* Otherwise, if the environment variable `__EGL_VENDOR_LIBRARY_DIRS` is set, it is a colon-separated list of directories. Each directory in turn is scanned for files named `*.json` and the ICDs that they describe are loaded. Files in the same directory are loaded in arbitrary order.

* If neither environment variable is set, GLVND behaves as though `__EGL_VENDOR_LIBRARY_DIRS` had been set to `${sysconfdir}/glvnd/egl_vendor.d:${datadir}/glvnd/egl_vendor.d`, replacing `${sysconfdir}` and `${datadir}` with the values that were set when GLVND was compiled.

* Each JSON file describing an ICD must have a JSON object at top level.
    * The key `file_format_version` must have a string value giving the file format `major.minor.micro` version number. This specification describes version `1.0.0`. Versions 1.0.x are required to be compatible with this specification, in the sense that an EGL loader that only implements file format version 1.0.0 will load all version 1.0.x JSON files successfully. Different major and minor versions might require loader changes.
    * The key `ICD` must have an object value.
        * In the `ICD` object, the key `library_path` must have a string value.
            * If the library path is a bare filename with no directory separators, for example `libEGL_mesa.so.0`, the loader is expected to search for it in the system's default runtime library directories.
            * If the library path is an absolute path, for example `/opt/myvendor/libEGL_myvendor.so`, the loader is expected to load the ICD from that absolute path.
            * If the library path is a relative path, for example `../lib/libEGL_myvendor.so`, [...TBD...]

## ICD installation

OS vendors should install JSON files into `${datadir}/glvnd/egl_vendor.d` where `${datadir}` is the data directory with which they configured GLVND, normally `/usr/share`.

Third-party vendors and sysadmins should usually install JSON files into `/etc/glvnd/egl_vendor.d`, on the assumption that GLVND was configured with `${sysconfdir}` set to `/etc`.

If a vendor installs ICD libraries into one of the system's default runtime library directories, they must install a JSON file referencing the ICD library by either its absolute path or its bare filename.

If a vendor installs ICD libraries into a non-standard directory, they must install a JSON file referencing the ICD library by its absolute path.

If a vendor installs matching ICD libraries for more than one ABI (for example 32- and 64-bit versions), each library has the same name, and each library is in a directory searched by default by the runtime linker and referenced by its bare filename, then they may install a single JSON file to describe all of those ICD libraries. For example, Mesa on Debian installs `/usr/lib/x86_64-linux-gnu/libEGL_mesa.so.0` and `/usr/lib/i386-linux-gnu/libEGL_mesa.so.0`, which can both be described by a JSON file with `"library_path": "libEGL_mesa.so.0"`. Similarly, Mesa on Arch Linux installs 64-bit `/usr/lib/libEGL_mesa.so.0` and 32-bit `/usr/lib32/libEGL_mesa.so.0`, with a similar JSON file, while some other distributions use `lib64` for 64-bit libraries.

## Questions

* If the `library_path` is a relative path containing `/`, for example `../libEGL_myvendor.so`, what is it relative to? At the moment it gets passed directly to `dlopen()`, so the answer is the current working directory of the process that loaded libEGL, which I suspect is not what anyone wants. The Vulkan loader interprets relative paths as relative to the JSON file, which I think is probably more useful, but perhaps it's too late to change this in EGL?

* Should the search path include more directories? Some obvious candidates include:
    * `/etc/glvnd/egl_vendor.d`, even if GLVND was installed with a different `${sysconfdir}`
    * `/usr/share/glvnd/egl_vendor.d`, even if GLVND was installed with a different `${datadir}`
    * the `${libdir}` (which is very platform-dependent, and might include things like `lib64` or `lib/x86_64-linux-gnu`)
    * the [XDG base directories](https://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html) (some of which are used in the reference Vulkan loader, although it seems to be searching them in a weird order and not entirely following the spec)

* Is it correct to say that third-party vendors should install to `/etc/glvnd/egl_vendor.d`? That effectively means they're assuming that GLVND's `${sysconfdir}` is `/etc` (which seems likely to be correct in practice).

**Comment by smcv** [comment]
> Files in the same directory are loaded in arbitrary order.

Correction: they seem to be loaded in lexicographic order (`strcmp()`).

**Comment by kbrenneman** [comment]
That description of the discovery process is accurate. Two additional points, though:
- In a setuid or setgid process, the environment variables are ignored.
- The JSON files in each directory are sorted before reading them, so the filenames control the order that libglvnd will try each vendor.

The library path in the JSON file is passed directly to dlopen, though that's really to accommodate absolute paths, not relative ones. A relative path probably isn't what anyone would want, though as far as I know, nobody's ever used one.

For where to put the JSON files, you can use pkg-config to find the values of ${sysconfdir} and ${datadir} -- see Mesa's makefiles for an example of that. For a build of libglvnd from the package manager, though, that's (almost?) always going to be /etc and /usr/share.

As for whether to install the JSON files to /etc or /usr/share, if you're installing the library itself somewhere under /usr, then the JSON file should probably also go under /usr/. If I recall correctly, part of the purpose of the /usr tree is that you could share it across multiple systems, so putting both the JSON and library files under /usr would keep it consistent.

As far as additional directories:
- The ${datadir} and ${sysconfdir} directories are configurable so that you can put them wherever you want. Hard-coding those paths would remove that capability.
- ${libdir} doesn't seem like it would add any benefit beyond what you can already use ${datadir} and ${sysconfdir} for.
- The XDG directories might be worth considering, since it would allow a non-root user to install their own ICD's. I don't know if that's useful enough to justify the added complication of computing those paths, though.

**Comment by smcv** [comment]
> A relative path probably isn't what anyone would want, though as far as I know, nobody's ever used one.

Perhaps that's best documented as "unspecified behaviour" for the moment, then.

Would you accept a patch to make it consistent with the reference Vulkan loader? That has the same three cases, but different behaviour in the third case:

* bare filename, e.g. `libEGL_mesa.so.0`: search the usual runtime library path (by passing it to `dlopen()`)
* absolute path, e.g. `/opt/myvendor/libEGL_myvendor.so`: use it as-is (by passing it to `dlopen()`)
* relative path, e.g. `./libEGL_myvendor.so`: turn it into an absolute path by interpreting it as relative to *the location of the JSON file*, and then pass the absolute path to `dlopen()`

**Comment by smcv** [comment]
> If I recall correctly, part of the purpose of the /usr tree is that you could share it across multiple systems, so putting both the JSON and library files under /usr would keep it consistent.

The interpretation in most Linux distributions is that `/usr` is controlled by the package manager, except for `/usr/local` which is controlled by the sysadmin.

**Comment by kbrenneman** [comment]
Sure. Keeping EGL a little more consistent with Vulkan is probably worthwhile, and I certainly can't think of any use for the current behavior for a relative path.

**Comment by smcv** [comment]
> The ${datadir} and ${sysconfdir} directories are configurable so that you can put them wherever you want. Hard-coding those paths would remove that capability.

What I meant here was that it might be worthwhile to look in a hard-coded directory *in addition to* the ones in GLVND's build-time configuration, so that there is a guaranteed location where ICD manifests will always be found. For example, the reference Vulkan loader always looks in `/etc`: if its own `${sysconfdir}` is different, it will look in its own `${sysconfdir}` first, and then in `/etc`.

Implementing one or both of the XDG config and data families effectively gives you this anyway, because the specification has some hard-coded defaults for the case where the variable isn't set (`/etc/xdg`, `/usr/local/share` and `/usr/share`). Unfortunately the reference Vulkan loader implements something that resembles, but is not quite, the XDG basedir spec (https://github.com/KhronosGroup/Vulkan-Loader/issues/245, https://github.com/KhronosGroup/Vulkan-Loader/issues/246).

**Comment by smcv** [comment]
> ${libdir} doesn't seem like it would add any benefit beyond what you can already use ${datadir} and ${sysconfdir} for.

The only benefit I had in mind was that the metadata describes ICD library binaries, and those are naturally architecture-specific anyway. For example, on x86 architectures, Debian and the Freedesktop SDK have `/usr/lib/x86_64-linux-gnu` vs. `/usr/lib/i386-linux-gnu` ("multiarch"), while Fedora and openSUSE have `/usr/lib64` vs. `/usr/lib` ("multilib"). If the absolute path to a 32-bit ICD was described by a file in the 32-bit `${libdir}`, then 64-bit processes wouldn't try to `dlopen()` it, and vice versa.

**Comment by kbrenneman** [comment]
Closing this one, now that we've got better documentation checked in.

**Comment by smcv** [comment]
> Keeping EGL a little more consistent with Vulkan is probably worthwhile, and I certainly can't think of any use for the current behavior for a relative path.

I opened #190 for this (sorry, no MR yet).
