### ISSUE TITLE
should interpret relative paths the same way Vulkan does

### ISSUE THREAD

**Issue by smcv** [NVIDIA/libglvnd#190]
On #187 I asked
> If the library_path is a relative path containing /, for example ../libEGL_myvendor.so, what is it relative to? At the moment it gets passed directly to dlopen(), so the answer is the current working directory of the process that loaded libEGL, which I suspect is not what anyone wants. The Vulkan loader interprets relative paths as relative to the JSON file, which I think is probably more useful
>
> Would you accept a patch to make it consistent with the reference Vulkan loader?

and @kbrenneman replied

> Sure. Keeping EGL a little more consistent with Vulkan is probably worthwhile, and I certainly can't think of any use for the current behavior for a relative path.

I'll try to do a MR for this at some point.

**Comment by kbrenneman** [comment]
Note that we're migrating libglvnd over to Freedesktop, so we'll want to continue the discussion (and post the merge request) over there:
https://gitlab.freedesktop.org/glvnd/libglvnd/issues/190

**Comment by smcv** [comment]
Closing in favour of the migrated version. I've added myself to cc there.
