### ISSUE TITLE
new release for meson build?

### ISSUE THREAD

**Issue by chenrui333** [NVIDIA/libglvnd#201]
👋  It looks like the most recent release 1.2.0 (which is about a year ago) does not have meson build config, I wonder if there is a new release in the near future for the meson build. Thanks!

**Comment by magiruuvelvet** [comment]
The project moved to https://gitlab.freedesktop.org/glvnd/libglvnd long time ago, this is also where the releases happen. The current version is `1.3.2`. The GitHub repo is basically dead and just kept intact for some reason.

**Comment by chenrui333** [comment]
I see, thanks @magiruuvelvet. I will checkout there then.
