### ISSUE TITLE
Build failure with meson 0.58.0

### ISSUE THREAD

**Issue by rezso** [NVIDIA/libglvnd#211]
Building with meson 0.58.0 fails:

`tests/meson.build:103:4: ERROR: List item must be one of <class 'str'>, not <class 'list'>`

As a workaround, I removed the `subdir('tests')` line from toplevel meson.build file.

**Comment by kbrenneman** [comment]
Libglvnd is hosted on freedesktop now, so any new bug reports need to get filed there:
https://gitlab.freedesktop.org/glvnd/libglvnd

**Comment by boegel** [comment]
See https://gitlab.freedesktop.org/glvnd/libglvnd/-/issues/218
