### ISSUE TITLE
using libglvnd & libOpenGL.so as a module in a non-standard path to load, LD_PRELOAD nor LD_LIBRARY_PATH seem to work

### ISSUE THREAD

**Issue by RobbieTheK** [NVIDIA/libglvnd#217]
We use a Bright Computing cluster on RHEL 7 which allows us to customize modules for users to load ad hoc and ideally we're looking for a way to keep up with changes/updates to libOpenGL.so. A common use case would be a user on a Mac, with XQuartz installed, will ssh with the -X or -Y flag(s) and start a program like mfix which has 3D visualization. I compiled and installed into `/path/to/libglvnd` and here are the files:
```
libglvnd]$ ls -l lib/
total 2624
-rwxr-xr-x 1 root root     979 Aug 30 11:41 libEGL.la
lrwxrwxrwx 1 root root      15 Aug 30 11:41 libEGL.so -> libEGL.so.1.1.0
lrwxrwxrwx 1 root root      15 Aug 30 11:41 libEGL.so.1 -> libEGL.so.1.1.0
-rwxr-xr-x 1 root root  125328 Aug 30 11:41 libEGL.so.1.1.0
-rwxr-xr-x 1 root root     962 Aug 30 11:40 libGLdispatch.la
lrwxrwxrwx 1 root root      22 Aug 30 11:40 libGLdispatch.so -> libGLdispatch.so.0.0.0
lrwxrwxrwx 1 root root      22 Aug 30 11:40 libGLdispatch.so.0 -> libGLdispatch.so.0.0.0
-rwxr-xr-x 1 root root 1033832 Aug 30 11:40 libGLdispatch.so.0.0.0
-rwxr-xr-x 1 root root    1002 Aug 30 11:41 libGLESv1_CM.la
lrwxrwxrwx 1 root root      21 Aug 30 11:41 libGLESv1_CM.so -> libGLESv1_CM.so.1.2.0
lrwxrwxrwx 1 root root      21 Aug 30 11:41 libGLESv1_CM.so.1 -> libGLESv1_CM.so.1.2.0
-rwxr-xr-x 1 root root   49232 Aug 30 11:41 libGLESv1_CM.so.1.2.0
-rwxr-xr-x 1 root root     984 Aug 30 11:41 libGLESv2.la
lrwxrwxrwx 1 root root      18 Aug 30 11:41 libGLESv2.so -> libGLESv2.so.2.1.0
lrwxrwxrwx 1 root root      18 Aug 30 11:41 libGLESv2.so.2 -> libGLESv2.so.2.1.0
-rwxr-xr-x 1 root root   87680 Aug 30 11:41 libGLESv2.so.2.1.0
-rwxr-xr-x 1 root root    1021 Aug 30 11:41 libGL.la
lrwxrwxrwx 1 root root      14 Aug 30 11:41 libGL.so -> libGL.so.1.7.0
lrwxrwxrwx 1 root root      14 Aug 30 11:41 libGL.so.1 -> libGL.so.1.7.0
-rwxr-xr-x 1 root root  715688 Aug 30 11:41 libGL.so.1.7.0
-rwxr-xr-x 1 root root     988 Aug 30 11:41 libGLX.la
lrwxrwxrwx 1 root root      15 Aug 30 11:41 libGLX.so -> libGLX.so.0.0.0
lrwxrwxrwx 1 root root      15 Aug 30 11:41 libGLX.so.0 -> libGLX.so.0.0.0
-rwxr-xr-x 1 root root  384520 Aug 30 11:41 libGLX.so.0.0.0
-rwxr-xr-x 1 root root     984 Aug 30 11:40 libOpenGL.la
lrwxrwxrwx 1 root root      18 Aug 30 11:40 libOpenGL.so -> libOpenGL.so.0.0.0
lrwxrwxrwx 1 root root      18 Aug 30 11:40 libOpenGL.so.0 -> libOpenGL.so.0.0.0
-rwxr-xr-x 1 root root  218440 Aug 30 11:40 libOpenGL.so.0.0.0
drwxr-xr-x 2 root root    4096 Aug 30 11:41 pkgconfig

```
I've set `LD_PRELOAD=/path/to/libglvnd/libOpenGL.so.0` as well as `LD_LIBRARY_PATH:$LD_LIBRARY_PATH:/path/to/libglvnd/lib`

I still get errors like:
`vtkOpenGLRenderWindow.c:499    ERR| vtkXOpenGLRenderWindow (0x55555d20c120): Unable to find a valid OpenGL 3.2 or later implementation. Please update your video card driver to the latest version. If you are using Mesa please make sure you have version 11.2 or later and make sure your driver in Mesa supports OpenGL 3.2 such as llvmpipe or openswr. If you are on windows and using Microsoft remote desktop note that it only supports OpenGL 3.2 with nvidia quadro cards. You can use other remoting software such as nomachine to avoid this issue.
`
If I install a recent cuda-driver package and libOpenGL is in `/usr/lib64 `all is well. Is there a service or something that needs to be linked to the kernel that is also needed for this use case?

**Comment by kbrenneman** [comment]
Libglvnd is hosted at freedesktop now, so any questions or bug reports should go there:
https://gitlab.freedesktop.org/glvnd/libglvnd
