### ISSUE TITLE
Compile error with libglvnd-1.2.0 - argument 1 of type ‘const GLdouble *’ {aka ‘const double *’} declared as a pointer [-Werror=array-parameter=]

### ISSUE THREAD

**Issue by rubyFeedback** [NVIDIA/libglvnd#219]
Hey there,

Just reporting this on my linux system today:

     CC libglapi_la-table.lo
     CCLD libglapi_gl.la
     CCLD libglapi_opengl.la
     CCLD libglapi_glesv1.la
     CC libglapi_glesv2_la-entry_simple_asm.lo
     CC libglapi_glesv2_la-entry_common.lo
     CC libglapi_glesv2_la-stub.lo
    In file included from ../../../../src/GLdispatch/vnd-glapi/mapi_tmp.h:34,
     from ../../../../src/GLdispatch/vnd-glapi/table.c:50:
    ../../../../src/GLdispatch/vnd-glapi/./glapi_mapi_tmp.h:1551:60: error: argument 1 of type ‘const GLdouble *’ {aka ‘const     double *’} declared as a pointer [-Werror=array-parameter=]
     1551 | GLAPI void APIENTRY glLoadTransposeMatrixd(const GLdouble *m);
     | ~~~~~~~~~~~~~~~~^
    In file included from ../../../../src/GLdispatch/vnd-glapi/glapi.h:48,
     from ../../../../src/GLdispatch/vnd-glapi/table.h:33,
     from ../../../../src/GLdispatch/vnd-glapi/table.c:31:
    ../../../../include/GL/gl.h:1933:62: note: previously declared as an array ‘const GLdouble[16]’ {aka ‘const double[16]’}
     1933 | GLAPI void GLAPIENTRY glLoadTransposeMatrixd( const GLdouble m[16] );
     | ~~~~~~~~~~~~~~~^~~~~
    ../../../../src/GLdispatch/vnd-glapi/./glapi_mapi_tmp.h:1553:59: error: argument 1 of type ‘const GLfloat *’ {aka ‘const float *’}     declared as a pointer [-Werror=array-parameter=]
     1553 | GLAPI void APIENTRY glLoadTransposeMatrixf(const GLfloat *m);
     | ~~~~~~~~~~~~~~~^
    ../../../../include/GL/gl.h:1935:61: note: previously declared as an array ‘const GLfloat[16]’ {aka ‘const float[16]’}
     1935 | GLAPI void GLAPIENTRY glLoadTransposeMatrixf( const GLfloat m[16] );
     | ~~~~~~~~~~~~~~^~~~~
    ../../../../src/GLdispatch/vnd-glapi/./glapi_mapi_tmp.h:1655:60: error: argument 1 of type ‘const GLdouble *’ {aka ‘const     double *’} declared as a pointer [-Werror=array-parameter=]
     1655 | GLAPI void APIENTRY glMultTransposeMatrixd(const GLdouble *m);
     | ~~~~~~~~~~~~~~~~^
    ../../../../include/GL/gl.h:1937:62: note: previously declared as an array ‘const GLdouble[16]’ {aka ‘const double[16]’}
     1937 | GLAPI void GLAPIENTRY glMultTransposeMatrixd( const GLdouble m[16] );
     | ~~~~~~~~~~~~~~~^~~~~
    ../../../../src/GLdispatch/vnd-glapi/./glapi_mapi_tmp.h:1657:59: error: argument 1 of type ‘const GLfloat *’ {aka ‘const float *’}     declared as a pointer [-Werror=array-parameter=]
     1657 | GLAPI void APIENTRY glMultTransposeMatrixf(const GLfloat *m);
     | ~~~~~~~~~~~~~~~^
    ../../../../include/GL/gl.h:1939:61: note: previously declared as an array ‘const GLfloat[16]’ {aka ‘const float[16]’}
     1939 | GLAPI void GLAPIENTRY glMultTransposeMatrixf( const GLfloat m[16] );
     | ~~~~~~~~~~~~~~^~~~~
     CCLD libglapi_glesv2.la
    cc1: all warnings being treated as errors
    make[4]: *** [Makefile:860: libglapi_la-table.lo] Error 1
    make[4]: *** Waiting for unfinished jobs....
    make[4]: Leaving directory '/home/x/Temp/rbt/libglvnd-1.2.0/BUILD_DIRECTORY/src/GLdispatch/vnd-glapi'
    make[3]: *** [Makefile:1317: install] Error 2
    make[3]: Leaving directory '/home/x/Temp/rbt/libglvnd-1.2.0/BUILD_DIRECTORY/src/GLdispatch/vnd-glapi'
    make[2]: *** [Makefile:573: install-recursive] Error 1
    make[2]: Leaving directory '/home/x/Temp/rbt/libglvnd-1.2.0/BUILD_DIRECTORY/src/GLdispatch'
    make[1]: *** [Makefile:400: install-recursive] Error 1
    make[1]: Leaving directory '/home/x/Temp/rbt/libglvnd-1.2.0/BUILD_DIRECTORY/src'
    make: *** [Makefile:489: install-recursive] Error 1

**Comment by kbrenneman** [comment]
Libglvnd is hosted on freedesktop now, so any new bug reports need to go there:
https://gitlab.freedesktop.org/glvnd/libglvnd
