### ISSUE TITLE
Unnecessary GPU wake-ups and ICD ordering (with proprietary NVIDIA driver)

### ISSUE THREAD

**Issue by Gert-dev** [NVIDIA/libglvnd#221]
On a hybrid system with an iGPU handled by mesa and an NVIDIA dGPU, the current proprietary NVIDIA driver gets precedence because it installs its own driver JSON file with priority 10, whilst mesa uses priority 50. Some GTK4 applications needing graphical acceleration such as Nautilus and BlackBox end up running on the iGPU anyway, which is intended behaviour. However, **because the NVIDIA driver is evaluated first, the dGPU is woken up anyway**, despite it passing up the opportunity to actually handle it.

Next to the unnecessary wakeup, these applications **also incur a delay of several seconds during start** when the NVIDIA dGPU is powered down, waiting for this spin-up to happen. The delay then stops happening for subsequent starts as long as the dGPU remains powered up.

A related Arch forum topic with more details can be found [here](https://bbs.archlinux.org/viewtopic.php?pid=2113296#p2113296). It is mentioned as a packaging issue and changing the priorities as workaround, but it may be more complex than this because there might potentially be configurations with hybrid GPU setups where the NVIDIA driver must have a higher priority and others where it may not.

Finally, it may be prudent to mention that Flatpaked applications have their own copy of GLVND and the matching JSON configurations.

(I wasn't sure where this issue specifically belongs, nor if it is an architectural problem with how GLVND works or if it's a specific driver problem, so I thought I'd start here.)

**Comment by kbrenneman** [comment]
Libglvnd is hosted at Freedesktop now, so any new bug reports should go there.

This particular issue has already been reported there (thought there's not much that can be done about it from the libglvnd side):
https://gitlab.freedesktop.org/glvnd/libglvnd/-/issues/240
