### ISSUE TITLE
Latest stable/recommended release 1.2 vs 1.6?

### ISSUE THREAD

**Issue by jcamposeco** [NVIDIA/libglvnd#223]
There are tags pointing to 1.6 version, where the releases point to a 2019 version 1.2
Could you please advise the recommended/stable version?
Thanks

**Comment by kbrenneman** [comment]
Libglvnd is hosted on freedesktop.org now, so the up-to-date releases page is there:
https://gitlab.freedesktop.org/glvnd/libglvnd/-/releases

The freedesktop.org repo set up to automatically mirror to the old GitHub repo, which copies the tags. But, if there's a way to make it mirror the release notes, then I've never found it.

My usual recommendation is to just use whatever version comes with your distro. If that's not an option (if you're deciding what version to put into a distro), then I'd recommend the most recent point release.
