### ISSUE TITLE
libGLdispatch: Race condition in PatchEntrypoints

### ISSUE THREAD

**Issue by kbrenneman** [NVIDIA/libglvnd#36]
libGLdispatch will try to let a vendor library patch the OpenGL entrypoints when there's a single thread with a current context. When a second thread calls MakeCurrent, then it'll restore those entrypoints to the original versions.

That means that the second thread might try to rewrite an entrypoint while the first thread is executing it.

**Comment by kbrenneman** [comment]
One possibility that I can think of is to add some scratch space after each entrypoint. The vendor library would write its versions into that scratch space, leaving the original entrypoint unmodified.

At the top of each entrypoint, it would then jump to one version or the other.

If there were an unconditional branch at the top, then libGLdispatch could rewrite that branch to point to the vendor library's code after the vendor library is finished patching. Restoring the original would just mean rewriting the jump so that it points back to the original code instead.

Alternately, it could be a conditional branch based on some global flag. Then, restoring the original entrypoints would just mean setting that flag.

The first thread (the one executing the entrypoint) will still be using the same context, and thus the same vendor library. As long as it uses one or the other, it'll be fine.

**Comment by kbrenneman** [comment]
Looking at it again, I think there actually isn't a race condition -- it'll just refuse to patch or unpatch the entrypoints at all if there's more than one current context.

So, it won't rewrite the entrypoints out from under another thread, but it would cause a MakeCurrent call to fail if two threads try to use contexts from different vendors.

**Comment by jidanni** [comment]
I am wondering if such race conditions would lead to the intermittent failures as in
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=869746 ?

**Comment by kbrenneman** [comment]
@jidanni -- No, it wouldn't. As I noted earlier, there isn't actually a race condition -- I was just misreading some of the related code.

In addition, GLVND doesn't use anything more elaborate than locks for communication between threads, and it doesn't have (or need) any sort of inter-process communication beyond xlib.

The actual drivers can be implemented however they want, but I'd have to go look into it to see if/how any driver uses signals internally. But either way, that's not going to change based on GLVND.

**Comment by jidanni** [comment]
OK thanks.
I will probably just implement a strace 2>/dev/null wrapper.
At least that will make my command work.

**Comment by kbrenneman** [comment]
Closing. As far as I can tell, MakeCurrent calls failing due to using different vendors on different threads has yet to be a problem for any real-world application. If that changes, we can revisit what to do about it.
