### ISSUE TITLE
fails to Installing the Package with `checkinstall` on Ubuntu 15.04

### ISSUE THREAD

**Issue by GlulkAlex** [NVIDIA/libglvnd#40]
after:
`libtool: install: warning: relinking libGLX.la'`
I have:
```
../../libtool: line 1099: cd: /../../Documents/NVIDIA: No such file or directory
/bin/bash: /../../Documents/NVIDIA: No such file or directory
libtool: install: error: relink `libGLX.la' with the above command before installing it
Makefile:453: recipe for target 'install-libLTLIBRARIES' failed
make[4]: *** [install-libLTLIBRARIES] Error 1
make[4]: Leaving directory '/../../Documents/libglvnd-master/src/GLX'
Makefile:661: recipe for target 'install-am' failed
make[3]: *** [install-am] Error 2
make[3]: Leaving directory '/../../Documents/libglvnd-master/src/GLX'
Makefile:655: recipe for target 'install' failed
make[2]: *** [install] Error 2
make[2]: Leaving directory '/../../Documents/libglvnd-master/src/GLX'
Makefile:367: recipe for target 'install-recursive' failed
make[1]: *** [install-recursive] Error 1
make[1]: Leaving directory '/../../Documents/libglvnd-master/src'
Makefile:421: recipe for target 'install-recursive' failed
make: *** [install-recursive] Error 1

****  Installation failed. Aborting package creation.
```
`relinking` definitely not work for me.
Does this mean that ***make*** was unsuccessful ? 
I have some fails notes about `.la` files, but at third attempt it seems to be alright.

**Comment by kbrenneman** [comment]
@GlulkAlex - What were the configure and make arguments that you used? Also, did you run configure in the root of the source directory, or in a different directory?

**Comment by GlulkAlex** [comment]
first I run
`./autogen.sh`
then 
`./configure`
then
`make` without any arguments 
all those I run from the same directory where the script files was - the root of the source directory.

**Comment by kbrenneman** [comment]
I can't reproduce that failure at all. From the output you're getting, though, something's really messed up in the configuration.

The paths that start with "/../../Documents/" look really weird. In particular, the "Entering/Leaving directory ..." lines should have the absolute pathnames to whatever the directory is, so I can't think of any way to make it print a path that starts with "/..".

In addition, running "make" without any arguments shouldn't run the install target at all. It should only try to install anything if you run "make install".

Do you get the same result if you clone a fresh copy of the source tree?

**Comment by GlulkAlex** [comment]
May by it was unclear that I was using 
[Installing the Package with `checkinstall`](https://help.ubuntu.com/community/CompilingSoftware)
I did that before because
> the legacy way of installing (not recommended)

and it works just fine.
So nothing fancy. 
Kyle, what do you mean by 
> clone a fresh copy of the source tree ?

You have recent updates, that can behave differently ? 
Ok, I will try this.
Thanks for heads up.

**Comment by kbrenneman** [comment]
Ah, I wasn't familiar with the checkinstall tool -- I thought you meant the install or installcheck Makefile target.

Using a fresh source tree was just to see if a bug in the configure script or a makefile had garbled something.

**Comment by kbrenneman** [comment]
@GlulkAlex - Are you running checkinstall as root?

As far as I can tell, checkinstall doesn't work as a non-root user, because make still has to copy files to /usr/, which it can't do as a non-root user. The --fstrans option doesn't help in this case because it doesn't know how to deal with a mkdir call.

**Comment by GlulkAlex** [comment]
As help.ubuntu.com suggest I use `sudo checkinstall` .
I follow you advice and clone a fresh copy of the source tree,
then compile the package in different directory 
(I have some issues with users from previous lubuntu installation)
and
have completely different error:
```
dpkg-deb: error: parsing file '/var/tmp/tmp.MY9SOihXOr/package/DEBIAN/control' near line 7 package 'libglvnd':
 error in 'Version' field string 'master-1': version number does not start with digit
/var/tmp/tmp.MY9SOihXOr/dpkgbuild.log (END)
``` 

after:
```
======================== Installation successful ==========================

Some of the files created by the installation are inside the home directory: /home

You probably don't want them to be included in the package.
Do you want me to list them?  [n]: y
Should I exclude them from the package? (Saying yes is a good idea)  [n]: y

Copying files to the temporary directory...OK

Stripping ELF binaries and libraries...OK

Compressing man pages...OK

Building file list...OK

Building Debian package... FAILED!
```
May be after next source update I will be lucky.

**Comment by GlulkAlex** [comment]
I can see indications that my issue has, probably, nothing to do with your library.
It is system specific. 
In particular related to slightly damaged users settings & configurations 
(yes, I'm doing that wrong)
Problem solved.
Case closed.
Thank you for your time.
