### ISSUE TITLE
Define an ABI for libEGL

### ISSUE THREAD

**Issue by kbrenneman** [NVIDIA/libglvnd#45]
To add support for EGL in libglvnd, we'll need to define an interface between libEGL and a vendor library.

We'd need to define how libEGL would select a vendor library, how it would map from EGL objects to vendor libraries, and how the dispatch functions for EGL extensions work.

At the most basic, each EGLDisplay would probably be associated with a single vendor, which is selected when the EGLDisplay is first created. That vendor would then apply to any contexts and drawables created under that display.

OpenGL functions would work the same way they do with GLX. libEGL just has to find the dispatch table for whatever vendor owns the current context and plug it into libGLdispatch.

Similarly, EGL display extensions could follow the same pattern as GLX extensions. Every display extension function (by definition) specifies an EGLDisplay, so the dispatch functions can use that to look up the correct vendor library to call.

Where things get more complicated is with platform extensions, client extensions, and OpenVG.

libEGL has to be able to figure out which vendor library to load to handle an eglGetPlatformDisplay call. If a vendor library can add new platform extensions without having to modify libEGL itself, then that means libEGL has to figure that out without knowing how to interpret the eglGetPlatformDisplay parameters by itself.

For EGL client extensions, a simple dispatch function like we'd use for GLX won't always work. For example, the dispatch function for eglQueryDevicesEXT would have to call into every vendor library, not just one of them. For a vendor library to supply a dispatch function like that, it would also have to define the interface that the dispatch function expects to find in every other vendor library. And again, libEGL would have to know which vendor library to load in order to find the dispatch function in the first place.

For OpenVG, it'll need to maintain a second current context and dispatch table. We could probably either add a second dispatch table to libGLdispatch or define a second libGLdispatch-like library for OpenVG. I'm also guessing that it's all right if adding another API requires changing libEGL itself.

**Comment by kbrenneman** [comment]
So far, every design I've been able to come up with requires some way for libEGL to enumerate and load every vendor library up front, even if it's only going to use one of them.

Depending on how it's set up, though, that might not be quite as bad an option as it seems at first glance.

Each vendor library could provide some way to check whether it can be used at all. For example, a hardware vendor library would check whether the appropriate hardware is present on the system. libEGL could then load a vendor library, check if it's supported, and then unload it if it's not. In that case, it would probably only need to keep a few vendor libraries loaded.

If loading, checking, and unloading each vendor library is fast enough, then the additional startup cost might be acceptable.

**Comment by cubanismo** [comment]
That's how Vulkan's loader frontend works.  I don't see an alternative way to support non-X11 backends either unless we mandated some kernel API to enumerate devices.

**Comment by kbrenneman** [comment]
Okay, here's what I'm working on for vendor enumeration.

Each vendor library will install a config file in some well-known directory, which would contain the name of the DSO to load. I can reuse the same format that Vulkan uses for this.

In any case, libEGL will scan that directory and load any vendor libraries that it finds there.

Then, when the app calls eglGetDisplay or eglGetPlatformDisplay, libEGL will iterate over the vendor libraries and forward the call to each of them until one succeeds. That way, libEGL doesn't need to know anything about any particular platform.

Now, one complication with that is that libEGL would need a separate query to find out what platform extensions each vendor library supports. When libEGL constructs the client string, it'll need to include every platform extension from every vendor library, but the rest of the client extensions would be limited to what libEGL itself supports.

**Comment by cubanismo** [comment]
Can't the loader just report a client extension string containing all the platform extensions it knows about?  It was asserted that all client extensions require modifying the loader/dispatcher, so I don't think that's an unreasonable requirement.  And, is it actually a problem if the loader "supports" e.g., platform_wayland, but none of the drivers do?  Won't that just mean all drivers fail to create a display for that platform?

**Comment by kbrenneman** [comment]
The main difference is that a platform extension doesn't add any new entrypoints, just new arguments for eglGetPlatformDisplay. All of the logic for making sense of those arguments lives in the vendor library, so libEGL doesn't have to care about it.

If libEGL doesn't do anything except poll each vendor library for a display, then adding support for a new platform extension just means adding it to libEGL's own extension string.

As an alternative, we could add more elaborate support for individual platforms to libEGL itself. Things like using x11glvnd to select a vendor library on X11. If we go that route, then platforms would be the same as normal client extensions.

I guess things might be a bit cleaner and/or more predictable if libEGL knows how to interpret each platform, especially if there are ever cases where two or more vendor libraries can support it.

But, that would also require defining the vendor selection logic for every platform within libEGL. And we'd want to avoid things like dragging in all the Wayland libraries on an X11 program.

**Comment by kbrenneman** [comment]
Actually now that I think about it, we might need to handle specific platforms to support eglGetDisplay (rather than eglGetPlatformDisplay) calls.

With multiple platforms, each vendor library might have a different notion of which platforms to try by default. I don't see a good way to get sensible results if we just blindly poll every vendor library.

**Comment by kbrenneman** [comment]
All right looking things over again, I think something like this could work:

For eglGetPlatformDisplay, libEGL can poll each vendor library. The platform is already known, so there's no guesswork. If a vendor library can support the platform, then it'll know how to interpret the other parameters. Each vendor should then be able to either return a valid EGLDisplay or else return EGL_NO_DISPLAY without any other errors.

If the app calls eglGetDisplay, then libEGL will try to guess what platform to use. Mesa has some logic that can at least identify some cases, which we could adapt for libglvnd.

Once libEGL picks a platform, it will use that to call into eglGetPlatformDisplay. That way, the behavior of eglGetDisplay will be consistent regardless of what vendor libraries are loaded, and libEGL itself can support any platform without requiring any modification.

@cubanismo -- James, are there any platforms where libEGL would have to interpret the arguments to eglGetPlatformDisplay on its own?

**Comment by cubanismo** [comment]
I think this assertion:

"If a vendor library can support the platform, then it'll know how to interpret the other parameters."

doesn't necessarily hold up.  Platforms' attribute lists can be extended by further extensions (This will be done for EGLDevice in the EGL_EXT_device_drm extension soon), so libEGL can't assume that just because a vendor lib is aware of a platform, it will be able to parse an arbitrary set of attributes.  It would have to know which extensions affect those attribute lists, and whether each vendor lib supports them.  That might mean libEGL needs to interpret the attribute list itself.

**Comment by kbrenneman** [comment]
In that case, would it be enough for the vendor library to return EGL_NO_DISPLAY if it sees an attribute that it doesn't recognize?

**Comment by cubanismo** [comment]
Yes, that should work.

I misread your first comment as saying libEGL would poll for platform support before calling eglGetPlatformDisplay() some how.  It should be sufficient to handle the NO_DISPLAY return value.  

However, libEGL may need to override the current EGL error value after the call and debug callback (See EGL_KHR_debug) during the  call to prevent the application from seeing the failed eglGetPlatformDisplay() call's side effects if some other vendor later succeeds.

**Comment by kbrenneman** [comment]
Hmm, that does raise the question of what to do with the error codes from each vendor library.

If the platform type is valid, but it can't create an EGLDisplay for it, then eglGetPlatformDisplay is supposed to return EGL_NO_DISPLAY without raising any other errors. But, if the platform type is not valid, then it's supposed to raise an EGL_BAD_PARAMETER error.

What if each vendor library also returned an error code, but didn't otherwise set or report an error directly? libEGL could then set the error code based on that:

- If any vendor library returns a valid EGLDisplay, then eglGetError should return EGL_SUCCESS.
- If no vendor library returns a valid EGLDisplay, but at least one vendor returns an error code of EGL_SUCCESS, then libEGL will assumee that the parameters are valid but it couldn't get a display for some other reason. In that case, eglGetGetError should also return EGL_SUCCESS.
- If no vendor library returns a valid EGLDisplay, and no vendor library returns an error code of EGL_SUCCESS, then eglGetError will return one of the error codes from a vendor library.

In that last case, though, there's the question of which error to return if we get different error codes from different vendor libraries.

**Comment by nwnk** [comment]
I think we want to make the interaction between EGL and GLX in the same process well-defined.

Assume libEGL's MakeCurrent logic exists, and looks analogous to that of current libGLX. If we do eglMakeCurrent followed by glXMakeCurrent, what will happen is:

* CommonMakeCurrent calls __glXGetCurrentAPIState, gets NULL, thinks "no current context"
* Since we have "no" current context we call InternalMakeCurrentDispatch
* InternalMakeCurrentDispatch calls __glDispatchMakeCurrent
* __glDispatchGetCurrentAPIState returns non-NULL because EGL API state is installed
* assert, sadness

That's pretty clearly not what we want. Possibilities for handling this:

1. Throw an error instead of asserting; this means deciding which error is least wrong, as there's no existing language for this class of problem in EGL or GLX.
2. The EGL context is unbound (as if you'd called eglMakeCurrent(dpy, EGL_NO_SURFACE, EGL_NO_SURFACE, EGL_NO_CONTEXT)) and the GLX context is bound; all state now points to GLX
3. EGL and GLX maintain separate notions of the "current context"; GLX takes over ownership of the global GLdispatch state, but function pointers acquired through eglGetProcAddress would still operate on the current EGL context.

3 seems... insane. Of the other two I think option 2 is probably more useful.  I don't think it requires too much more than treating "change of API" like "change of vendor" in CommonMakeCurrent, but I'm not sure I've thought it through all the way.

**Comment by cubanismo** [comment]
(1) sounds good to me.  Since GLVND is managing TLS now, it seems reasonable for it to be able to check for this (Unlike when it may have been two separate vendors' drivers doing EGL Vs GLX TLS), but given the lack of specified behavior, I'd like to keep the interaction minimal.  We should probably revive efforts to formally define this interaction at the Khronos level.

**Comment by cubanismo** [comment]
FWIW, though I agree it's insane, our driver currently does (3) because of... I won't bore you, but not great reasons.

**Comment by kbrenneman** [comment]
I would lean toward (1) as well.

Returning an error would be trivial to implement. eglMakeCurrent and glXMakeCurrent would just check the current __GLdispatchAPIState::tag value, and return an error if the current context belongs to a different API.

Option (2) would be possible, but it would be more complicated and probably more error-prone. The best way I've thought of to do that would be to add another callback to the __GLdispatchAPIState struct, similar to how it handles thread termination. I'd expect that switching between EGL and GLX would be an uncommon use case, and an application can just release the current context manually if it needs to. So, this doesn't seem like it would be worth the complexity.

Option (3) couldn't work at all with libglvnd, because there's only one set of OpenGL entrypoints which are used for both EGL and GLX. Everything goes through libGLdispatch.so, and there'd be no way to decide which context to use for dispatching.

**Comment by nwnk** [comment]
EGL_NV_system_time seems difficult to support in this model. No matter where it lives - in libEGL or in the vendor libraries - everyone implementing it would have to agree. (Presumably this would be the same "system time" as in the MST in swap control extensions...)

EGL_NV_sync would need some amount of support from libEGL to be able to look up the vendor from the EGLSyncNV. In this particular case it might not matter much as I think the KHR sync extensions have overtaken it, but the general point stands; we'd need something like `__glXAddVendorDrawableMapping`, either one for every new type that might determine dispatch, or one for every opaque pointer at all. (The same would be true of a new GLX function that didn't have a Display in its function signature.)

EGL_KHR_debug needs to be special-cased in libEGL as well.

**Comment by kbrenneman** [comment]
For EGL_NV_system_time, I don't think mismatched implementations could work under any model. Since the functions in it don't take any parameters, it would have to be implemented in libEGL itself, and any vendor library would have to cope with whatever that implementation is. It's an NV extension, though, so I don't know if anyone else implements it anyway.

For EGL_NV_sync, we would have to add a mapping for EGLSyncNV handles for vendor-provided dispatch stubs to work. I'd lean a little more toward a single generic pointer mapping instead of per-type, since it would have the least churn in the interface. It would need a similar uniqueness requirement to GLXFBConfig handles to make sure that two vendors don't trip over each other, though.

And for EGL_KHR_debug, we would probably need to add some additional callbacks to the ABI. I expect that will be true of most client extensions, though.

**Comment by cubanismo** [comment]
I really hate NV_system_time.  Do we need to support it, or can we just update the spec in the registry to declare it deprecated and incompatible with GLVND?

For EGL_KHR_debug, agreed, by definition almost all client extensions would require modification to the standard libEGL.so.  That was one of the the main purposes for differentiating client extensions in the first place, besides providing a way to query support for them.

**Comment by nwnk** [comment]
Mesa doesn't implement NV_system_time, and I don't see anyone asking for it to.

**Comment by kbrenneman** [comment]
From a closer look at it, there is one thing that could pose a problem for EGL_KHR_debug.

The EGL_KHR_debug extension requires an error callback any time a function generates an EGL error. The callback, in turn, requires a string of the EGL function name at a bare minimum.

That basically requires that every vendor has at least some limited support for EGL_KHR_debug so that it can provide that name along with any errors that it might raise.
