### ISSUE TITLE
The "correct" way to limit the exported symbols

### ISSUE THREAD

**Issue by evelikov** [NVIDIA/libglvnd#61]
According to Ulrich Drepper’s paper [1] the current method used in GLVND is the least desirable. The alternatives - annotating the symbols (a) and version scripts (b) being the other options.

Each of them has its drawbacks I'm afraid 
 a) annotating all the private symbols is tedious. f we go for the public ones, the declaration and definitions much have the PUBLIC tag. Which in itself will become part of the API and is likely to conflict with other symbols.
 b) older linkers (like the one in OpenBSD) do not support version scripts.

For most of mesa I've picked b) so I'm wondering if we don't want something similar here.

Thoughts, suggestions ?
-Emil

[1] http://people.redhat.com/drepper/dsohowto.pdf, whic

**Comment by kbrenneman** [comment]
Libtool actually has an option for exactly this. The -export-symbols option gives it a file with a list of symbols that the library should export, and then libtool figures out how to make that work on a given system. On Linux, it'll generate a version script to pass to the linker.

libGLdispatch.so and the entrypoint libraries all use that option, along with another script to generate the export lists for each library. libGLX.so doesn't use it yet, but probably ought to.

**Comment by evelikov** [comment]
Yes the project currently uses -export-symbols, which according to my earlier experiences (and the mentioned paper) produces suboptimal results. Namely it used to throw all the symbols over the fence (killing the local symbols needed for relocation) and then "cherry-pick" the listed once. Things may have improved since then, although others are likely to use an old/suboptimal version of libtool. Feel free to check the linked paper for the gory details :-)

**Comment by kbrenneman** [comment]
This project is the first time I've used libtool to any extent, so I don't know when the -export-symbols option was fixed.

Generating and using a version script manually might be an option, if we find that some systems have problems with older versions of libtool.

For libGLX.so and libGLdispatch.so, using the PUBLIC annotations actually isn't a bad option. The set of exported functions is pretty small and doesn't change much.

The main reason I didn't go with that for libGLdispatch.so is that I couldn't figure out how to set the visibility with functions that are only defined in assembly.

**Comment by evelikov** [comment]
I'm serious contemplating the proper annotation route... esp since the _init/_fini are missing in some libraries. That obviously I can deal with at later point.
Out of curiosity - are you aiming (in the future) to have things working with other (non gcc and clang/llvm) compilers the Sun/Oracle compiler and/or others ?

**Comment by kbrenneman** [comment]
At some point, maybe. It depends how much call there is for libglvnd on other systems, and how much effort it would take to maintain.

**Comment by kbrenneman** [comment]
> I'm seriously contemplating the proper annotation route... esp since the _init/_fini are missing in some libraries. That obviously I can deal with at later point.

The _init/_fini symbols are purely internal. The fact that they're exported in any library is just a quirk of the compiler and linker.

Of the various options, I'd be inclined to use an export list or version script. I think those will make it easier to ensure that extra symbols don't accidentally creep into any library.

If there's concern about using versions of libtool that don't do the right thing with -export-symbols, then I'd be fine with just using a version script directly.

**Comment by evelikov** [comment]
The most flexible solution is proper annotation - this way if we get 'broken' libtool (wrt export-symbols) or old one (missing version scripts) things will be fine. By annotating things the project will also be compatible with other compilers - Sun/Oracle one at the very least.

I'd say you need not worry about this - I'll get to it at some point.

**Comment by kbrenneman** [comment]
Closing. At this point, all of libglvnd's libraries either use a version script or annotations to control exported symbols.
