### ISSUE TITLE
Provide SLI support?

### ISSUE THREAD

**Issue by rfkrocktk** [NVIDIA/libglvnd#67]
Does this library potentially allow me to run multiple NVIDIA GPUs in SLI mode, each with each one outputting to its own monitor?

It's been a while since I checked, but it was my understanding that SLI didn't work on Linux yet.

**Comment by kbrenneman** [comment]
SLI is supported on Linux, and has been for quite a while.

In addition, SLI lets you drive a single screen with multiple GPU's. For running two screens on separate GPU's, you're looking at separate X screens, optionally with Xinerama.

Libglvnd operates on a per-screen basis, so SLI and Xinerama are orthogonal to it. In all cases, libglvnd just sees an X screen and looks up a vendor library for it. The vendor library is then responsible for everything else.

The only case that libglvnd changes is that it will let you have separate X screens on different GPU's made by different vendors.
