### ISSUE TITLE
[Ubuntu 16.04](361.28) native resolution doesn't fix the screen, it's a square

### ISSUE THREAD

**Issue by Scellow** [NVIDIA/libglvnd#68]
Native resolution is fucked up

When i select my native resolution 1680x1050 (16/10) it's just a square (stretched view)

If i set a different resolution it works fine, only the driver provided by ubuntu works fine

PS: I'm not sure if it's the right place to report this issue, so sorry in advance

**Comment by aaronp24** [comment]
libglvnd doesn't handle screen resolutions, it just sets up OpenGL communication between the application and the driver. If you're having trouble with the NVIDIA graphics drivers, you can email linux-bugs@nvidia.com.

**Comment by Scellow** [comment]
I sent a mail, thanks!
