### ISSUE TITLE
Check in a script to generate GLX dispatch stubs

### ISSUE THREAD

**Issue by kbrenneman** [NVIDIA/libglvnd#75]
Even though the GLX dispatch stubs are supposed to be provided by the vendor library, by definition the stubs for any common functions are going to be functionally identical.

It would be nice to have a script checked in that other developers can use and/or adapt to generate those stubs, rather than every vendor library duplicating the entire effort.

**Comment by evelikov** [comment]
If you're talking about the gen_scrn_dispatch.pl used to generate the below files in mesa, yes please.
If we can make sure it gets installed via `make install' that would be amazing.

```
g_glxglvnddispatchfuncs.c
g_glxglvnddispatchindices.h
```

**Comment by kbrenneman** [comment]
Same idea as the gen_scrn_dispatch.pl script, but I was actually planning on writing up a Python script so that it can re-use the same XML parsing logic as the other scripts.

Installing it from a "make install" wouldn't make sense, though, since a vendor library would typically need to adjust the script or the function lists to match the functions that the vendor library supports.

**Comment by kbrenneman** [comment]
We've migrated the repository over to GitLab, so this is now tracked at https://gitlab.freedesktop.org/glvnd/libglvnd/issues/75.
