### ISSUE TITLE
libglvnd breaks gnome

### ISSUE THREAD

**Issue by hussamT** [NVIDIA/libglvnd#82]
this is a downstream bug report https://bugs.archlinux.org/task/48770
it was working in a check out from the 15th then broke on the 29th.
Additionally if I try to compile any package using libgl when installing the 29th snapshot, i get undefined references to somethinggldispatchsomething.

**Comment by kbrenneman** [comment]
I assume this is with the NVIDIA driver package?

The recent batch of changes include a lot of interface changes, which aren't compatible with the current NVIDIA driver.

**Comment by kbrenneman** [comment]
Oh, yeah, I somehow missed the note that this is with 361.42.

361.42 will work with af2aeb0b4293e085ad61eae08be34e52f9d7b389 or before. Our next updated driver will work with c5bcda3b848fe52d6ae6ef25c917431c06d62d27 or later.

**Comment by hussamT** [comment]
On Thu, 2016-03-31 at 07:29 -0700, Kyle Brenneman wrote:
> I assume this is with the NVIDIA driver package?
> The recent batch of changes include a lot of interface changes, which
> aren't compatible with the current NVIDIA driver.

yes. the one just released yesterday 361.42.

**Comment by hussamT** [comment]
Ok, thank you. I'll close this bug report and ask the arch linux package maintainer to downgrade to a working revision. Thanks again for the quick reply.
